<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        DB::table('brands')->insert([
            ['name' => 'Google', 'category' => 'miscellaneous'],
            ['name' => 'Amazon', 'category' => 'miscellaneous'],
            ['name' => 'Samsung', 'category' => 'miscellaneous'],
            ['name' => 'Apple', 'category' => 'miscellaneous'],
            ['name' => 'Xiaomi', 'category' => 'miscellaneous'],
            ['name' => 'Microsoft', 'category' => 'operating_system'],
            ['name' => 'Nokia', 'category' => 'device'],
            ['name' => 'Sony', 'category' => 'miscellaneous'],
            ['name' => 'Huawei', 'category' => 'miscellaneous'],
            ['name' => 'LG', 'category' => 'miscellaneous'],
            ['name' => 'Motorola', 'category' => 'device'],
            ['name' => 'Lenovo', 'category' => 'miscellaneous'],
            ['name' => 'Dell', 'category' => 'device'],
            ['name' => 'HP', 'category' => 'device'],
            ['name' => 'Asus', 'category' => 'miscellaneous'],
            ['name' => 'Acer', 'category' => 'device'],
            ['name' => 'OnePlus', 'category' => 'device'],
            ['name' => 'Oppo', 'category' => 'device'],
            ['name' => 'Realme', 'category' => 'device'],
            ['name' => 'Vivo', 'category' => 'device'],
            ['name' => 'TCL', 'category' => 'device'],
            ['name' => 'ZTE', 'category' => 'device'],
            ['name' => 'Honor', 'category' => 'device'],
            ['name' => 'BlackBerry', 'category' => 'device'],
            ['name' => 'Panasonic', 'category' => 'miscellaneous'],
            ['name' => 'Philips', 'category' => 'miscellaneous'],
            ['name' => 'Nintendo', 'category' => 'device'],
            ['name' => 'Sega', 'category' => 'device'],
            ['name' => 'Atari', 'category' => 'device'],
            ['name' => 'Logitech', 'category' => 'device'],
            ['name' => 'Intel', 'category' => 'processor'],
            ['name' => 'AMD', 'category' => 'processor'],
            ['name' => 'NVIDIA', 'category' => 'graphics_card'],
            ['name' => 'Qualcomm', 'category' => 'processor'],
            ['name' => 'Broadcom', 'category' => 'processor'],
            ['name' => 'Texas Instruments', 'category' => 'processor'],
            ['name' => 'Marvell', 'category' => 'processor'],
            ['name' => 'MediaTek', 'category' => 'processor'],
            ['name' => 'Samsung Electronics', 'category' => 'storage'],
            ['name' => 'Micron Technology', 'category' => 'memory'],
            ['name' => 'Western Digital', 'category' => 'storage'],
            ['name' => 'Seagate Technology', 'category' => 'storage'],
            ['name' => 'Kingston Technology', 'category' => 'memory'],
            ['name' => 'Corsair', 'category' => 'memory'],
            ['name' => 'Crucial', 'category' => 'memory'],
            ['name' => 'Alienware', 'category' => 'device'],
            ['name' => 'MSI', 'category' => 'miscellaneous'],
            ['name' => 'Gigabyte', 'category' => 'miscellaneous'],
            ['name' => 'Razer', 'category' => 'device'],
            ['name' => 'Shuttle', 'category' => 'device'],
            ['name' => 'Synology', 'category' => 'storage'],
            ['name' => 'QNAP', 'category' => 'storage'],
            ['name' => 'Netgear', 'category' => 'network'],
            ['name' => 'Ubiquiti', 'category' => 'network'],
            ['name' => 'TP-Link', 'category' => 'network'],
            ['name' => 'D-Link', 'category' => 'network'],
            ['name' => 'Bosch', 'category' => 'miscellaneous'],
            ['name' => 'Somfy', 'category' => 'domotics'],
            ['name' => 'Legrand', 'category' => 'domotics'],
            ['name' => 'Nest', 'category' => 'domotics'],
            ['name' => 'Ring', 'category' => 'domotics'],
            ['name' => 'Arlo', 'category' => 'domotics'],
            ['name' => 'Netatmo', 'category' => 'domotics'],
            ['name' => 'Withings', 'category' => 'health'],
            ['name' => 'Fitbit', 'category' => 'health'],
            ['name' => 'Garmin', 'category' => 'health'],
            ['name' => 'PlayStation', 'category' => 'device'],
            ['name' => 'Xbox', 'category' => 'device'],
            ['name' => 'Steam', 'category' => 'operating_system'],
            ['name' => 'Valve', 'category' => 'device'],
            ['name' => 'Logitech G', 'category' => 'device'],
            ['name' => 'HyperX', 'category' => 'memory'],
            ['name' => 'SteelSeries', 'category' => 'device'],
            ['name' => 'Elgato', 'category' => 'device'],
            ['name' => 'AOC', 'category' => 'device'],
            ['name' => 'BenQ', 'category' => 'device'],
            ['name' => 'ViewSonic', 'category' => 'device'],
            ['name' => 'Pioneer', 'category' => 'audio'],
            ['name' => 'Yamaha', 'category' => 'audio'],
            ['name' => 'Denon', 'category' => 'audio'],
            ['name' => 'Marantz', 'category' => 'audio'],
            ['name' => 'Harman Kardon', 'category' => 'audio'],
            ['name' => 'JBL', 'category' => 'audio'],
            ['name' => 'Sennheiser', 'category' => 'audio'],
            ['name' => 'Creative', 'category' => 'audio'],
            ['name' => 'Toshiba', 'category' => 'storage'],
            ['name' => 'Fujitsu', 'category' => 'device'],
            ['name' => 'Sharp', 'category' => 'device'],
            ['name' => 'Alcatel', 'category' => 'device'],
            ['name' => 'Fairphone', 'category' => 'device'],
            ['name' => 'Realtek', 'category' => 'processor'],
            ['name' => 'Supermicro', 'category' => 'server'],
            ['name' => 'Cisco', 'category' => 'network'],
            ['name' => 'Asrock', 'category' => 'device'],
            ['name' => 'EVGA', 'category' => 'graphics_card'],
            ['name' => 'Plex', 'category' => 'operating_system'],
            ['name' => 'WD', 'category' => 'storage'],
            ['name' => 'Sandisk', 'category' => 'storage'],
            ['name' => 'G.Skill', 'category' => 'memory'],
            ['name' => 'Patriot', 'category' => 'memory'],
            ['name' => 'TeamGroup', 'category' => 'memory'],
            ['name' => 'ADATA', 'category' => 'memory'],
            ['name' => 'PNY', 'category' => 'memory'],
            ['name' => 'Inno3D', 'category' => 'graphics_card'],
            ['name' => 'Palit', 'category' => 'graphics_card'],
            ['name' => 'Sapphire', 'category' => 'graphics_card'],
            ['name' => 'PowerColor', 'category' => 'graphics_card'],
            ['name' => 'GALAX', 'category' => 'graphics_card'],
            ['name' => 'Colorful', 'category' => 'graphics_card'],
            ['name' => 'Kingmax', 'category' => 'memory'],
            ['name' => 'Silicon Power', 'category' => 'memory'],
            ['name' => 'Transcend', 'category' => 'memory'],
            ['name' => 'Apacer', 'category' => 'memory'],
            ['name' => 'Lexar', 'category' => 'memory'],
            ['name' => 'SK hynix', 'category' => 'memory'],
            ['name' => 'Toshiba Memory', 'category' => 'memory'],
            ['name' => 'OCZ', 'category' => 'storage'],
            ['name' => 'Mushkin', 'category' => 'memory'],
            ['name' => 'VisionTek', 'category' => 'graphics_card'],
            ['name' => 'Matrox', 'category' => 'graphics_card'],
            ['name' => 'XFX', 'category' => 'graphics_card'],
            ['name' => 'Biostar', 'category' => 'device'],
            ['name' => 'Jetway', 'category' => 'device'],
            ['name' => 'Foxconn', 'category' => 'miscellaneous'],
            ['name' => 'ARM', 'category' => 'processor'],
            ['name' => 'IBM', 'category' => 'processor'],
            ['name' => 'Freescale', 'category' => 'processor'],
        ]);
    }

    public function down(): void
    {
        //
    }
};
